name: fusion_app_store
description: The Fusion App Store
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  url_launcher: ^6.1.12
  device_info_plus: ^9.0.3
  get: ^4.6.5
  youtube_player_iframe: ^4.0.4
  http: ^1.1.0
  uuid: ^3.0.7
  responsive_framework: ^1.1.0
  flutter_clean_architecture: ^5.0.4
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  flutter_animate: ^4.2.0+1
  flutter_spinkit: ^5.2.0
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.11.1
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/backgrounds/
    - assets/animations/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
          weight: 400
        - asset: fonts/Sen/Sen-Medium.ttf
          weight: 500
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
